### ISSUE TITLE
scope2claims missing

### ISSUE THREAD

**Issue by jschlyter** [IdentityPython/JWTConnect-Python-OidcMsg#5]
`oidcmsg.oidc.scope2claims` was removed in 109f86ae4163e08350c95c479c7b201480ea13e3, but is required in ealier versions of `oidcendpoint`. Tricky to loose this in a patchlevel release. Fixed with hard dependency on `oidcendpoint==0.8.4` and `oidcmsg==0.6.3`.

**Comment by rohe** [comment]
:-(
Was moved to oidcendpoint. Part of an overhaul including locally defined scopes and claims.
