### ISSUE TITLE
[Suggestion] Add predefined claim specification list of dictionaries

### ISSUE THREAD

**Issue by jpslopes** [IdentityPython/JWTConnect-Python-OidcMsg#6]
Hello, I noticed that the list of dictionaries is not a predefined claim specification from message.py.

It is only a suggestion, but it could be useful to have the following claim specifications:
```python
REQUIRED_LIST_OF_DICTS = ([dict], True, list_serializer, list_deserializer, False)
OPTIONAL_LIST_OF_DICTS = ([dict], False, list_serializer, list_deserializer, False)
```

Thanks

**Comment by rohe** [comment]
Any special usage in mind ?
I'm not against adding the specifications just curious.

**Comment by jpslopes** [comment]
I think it could be useful when a given claim corresponds to a list of JSON objects.

**Comment by jpslopes** [comment]
Hello, sorry for bothering, but I would like to know if the claim specifications suggested above will be added in a future release. If yes, when do you think it could be?

Thanks

**Comment by rohe** [comment]
I've added it. Just did a release the other day so we missed that.
But I can do another release end of this week or beginning of next.

**Comment by jpslopes** [comment]
Thanks!
