### ISSUE TITLE
Empty list raises MissingRequiredAttribute when the attribute is required

### ISSUE THREAD

**Issue by jpslopes** [IdentityPython/JWTConnect-Python-OidcMsg#7]
Hello, I noticed that if an attribute in **c_param** is set with the specification `REQUIRED_LIST_OF_STRINGS`,  it will raise **MissingRequiredAttribute** when the corresponding value is an empty list.

I'm not sure this is the expected behavior...

Thanks

**Comment by rohe** [comment]
An empty list is the same thing as no value/list which is an error if the value is required.
So, yes !

**Comment by jpslopes** [comment]
Ok, thanks
