### ISSUE TITLE
Only .egg in PyPI for version 1.0.0

### ISSUE THREAD

**Issue by angelakis** [IdentityPython/JWTConnect-Python-OidcMsg#9]
Hello, could you release version 1.0.0 as a .tar.gz or a .whl, as pip afaik does not support .egg format?

Thanks!

**Comment by rohe** [comment]
I'll see what I can do. I've added sdist to the pypi distributions in .travis.yml which means that the next time we change version we should have a .tar.gz built automatically and pushed to pypi.

**Comment by angelakis** [comment]
Great, sdist will solve the problem. Just know that til the next release, oidcendpoint cannot be installed with pip:

```
ERROR: Could not find a version that satisfies the requirement oidcmsg>=1.0.0 (from oidcendpoint==1.0.1->SATOSA==6.1.0) (from versions: 0.3.0, 0.3.1, 0.3.3, 0.3.4, 0.3.5, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.6.10)
ERROR: No matching distribution found for oidcmsg>=1.0.0 (from oidcendpoint==1.0.1->SATOSA==6.1.0)
```

**Comment by rohe** [comment]
Just pushed oidcmsg 1.0.1
